/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.punktozaur.avro.loyalty;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SubtractPointsCommandAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8861911843551693860L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SubtractPointsCommandAvroModel\",\"namespace\":\"pl.punktozaur.avro.loyalty\",\"fields\":[{\"name\":\"loyaltyAccountId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"points\",\"type\":\"int\"},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<SubtractPointsCommandAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SubtractPointsCommandAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SubtractPointsCommandAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SubtractPointsCommandAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SubtractPointsCommandAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SubtractPointsCommandAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SubtractPointsCommandAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SubtractPointsCommandAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SubtractPointsCommandAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID loyaltyAccountId;
  private int points;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SubtractPointsCommandAvroModel() {}

  /**
   * All-args constructor.
   * @param loyaltyAccountId The new value for loyaltyAccountId
   * @param points The new value for points
   * @param createdAt The new value for createdAt
   */
  public SubtractPointsCommandAvroModel(java.util.UUID loyaltyAccountId, java.lang.Integer points, java.time.Instant createdAt) {
    this.loyaltyAccountId = loyaltyAccountId;
    this.points = points;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return loyaltyAccountId;
    case 1: return points;
    case 2: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: loyaltyAccountId = (java.util.UUID)value$; break;
    case 1: points = (java.lang.Integer)value$; break;
    case 2: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'loyaltyAccountId' field.
   * @return The value of the 'loyaltyAccountId' field.
   */
  public java.util.UUID getLoyaltyAccountId() {
    return loyaltyAccountId;
  }


  /**
   * Sets the value of the 'loyaltyAccountId' field.
   * @param value the value to set.
   */
  public void setLoyaltyAccountId(java.util.UUID value) {
    this.loyaltyAccountId = value;
  }

  /**
   * Gets the value of the 'points' field.
   * @return The value of the 'points' field.
   */
  public int getPoints() {
    return points;
  }


  /**
   * Sets the value of the 'points' field.
   * @param value the value to set.
   */
  public void setPoints(int value) {
    this.points = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new SubtractPointsCommandAvroModel RecordBuilder.
   * @return A new SubtractPointsCommandAvroModel RecordBuilder
   */
  public static pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder newBuilder() {
    return new pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder();
  }

  /**
   * Creates a new SubtractPointsCommandAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SubtractPointsCommandAvroModel RecordBuilder
   */
  public static pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder newBuilder(pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder other) {
    if (other == null) {
      return new pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder();
    } else {
      return new pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new SubtractPointsCommandAvroModel RecordBuilder by copying an existing SubtractPointsCommandAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new SubtractPointsCommandAvroModel RecordBuilder
   */
  public static pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder newBuilder(pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel other) {
    if (other == null) {
      return new pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder();
    } else {
      return new pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for SubtractPointsCommandAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SubtractPointsCommandAvroModel>
    implements org.apache.avro.data.RecordBuilder<SubtractPointsCommandAvroModel> {

    private java.util.UUID loyaltyAccountId;
    private int points;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.loyaltyAccountId)) {
        this.loyaltyAccountId = data().deepCopy(fields()[0].schema(), other.loyaltyAccountId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.points)) {
        this.points = data().deepCopy(fields()[1].schema(), other.points);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing SubtractPointsCommandAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.loyaltyAccountId)) {
        this.loyaltyAccountId = data().deepCopy(fields()[0].schema(), other.loyaltyAccountId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.points)) {
        this.points = data().deepCopy(fields()[1].schema(), other.points);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'loyaltyAccountId' field.
      * @return The value.
      */
    public java.util.UUID getLoyaltyAccountId() {
      return loyaltyAccountId;
    }


    /**
      * Sets the value of the 'loyaltyAccountId' field.
      * @param value The value of 'loyaltyAccountId'.
      * @return This builder.
      */
    public pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder setLoyaltyAccountId(java.util.UUID value) {
      validate(fields()[0], value);
      this.loyaltyAccountId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'loyaltyAccountId' field has been set.
      * @return True if the 'loyaltyAccountId' field has been set, false otherwise.
      */
    public boolean hasLoyaltyAccountId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'loyaltyAccountId' field.
      * @return This builder.
      */
    public pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder clearLoyaltyAccountId() {
      loyaltyAccountId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'points' field.
      * @return The value.
      */
    public int getPoints() {
      return points;
    }


    /**
      * Sets the value of the 'points' field.
      * @param value The value of 'points'.
      * @return This builder.
      */
    public pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder setPoints(int value) {
      validate(fields()[1], value);
      this.points = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'points' field has been set.
      * @return True if the 'points' field has been set, false otherwise.
      */
    public boolean hasPoints() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'points' field.
      * @return This builder.
      */
    public pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder clearPoints() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[2], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public pl.punktozaur.avro.loyalty.SubtractPointsCommandAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SubtractPointsCommandAvroModel build() {
      try {
        SubtractPointsCommandAvroModel record = new SubtractPointsCommandAvroModel();
        record.loyaltyAccountId = fieldSetFlags()[0] ? this.loyaltyAccountId : (java.util.UUID) defaultValue(fields()[0]);
        record.points = fieldSetFlags()[1] ? this.points : (java.lang.Integer) defaultValue(fields()[1]);
        record.createdAt = fieldSetFlags()[2] ? this.createdAt : (java.time.Instant) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SubtractPointsCommandAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<SubtractPointsCommandAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SubtractPointsCommandAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<SubtractPointsCommandAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










